#!/usr/bin/env python3
"""
--- Part Two ---

Before you can give the destination to the captain, you realize that the actual action meanings were printed on the back of the instructions the whole time.

Almost all of the actions indicate how to move a waypoint which is relative to the ship's position:

    Action N means to move the waypoint north by the given value.
    Action S means to move the waypoint south by the given value.
    Action E means to move the waypoint east by the given value.
    Action W means to move the waypoint west by the given value.
    Action L means to rotate the waypoint around the ship left (counter-clockwise) the given number of degrees.
    Action R means to rotate the waypoint around the ship right (clockwise) the given number of degrees.
    Action F means to move forward to the waypoint a number of times equal to the given value.

The waypoint starts 10 units east and 1 unit north relative to the ship. The waypoint is relative to the ship; that is, if the ship moves, the waypoint moves with it.

For example, using the same instructions as above:

    F10 moves the ship to the waypoint 10 times (a total of 100 units east and 10 units north), leaving the ship at east 100, north 10. The waypoint stays 10 units east and 1 unit north of the ship.
    N3 moves the waypoint 3 units north to 10 units east and 4 units north of the ship. The ship remains at east 100, north 10.
    F7 moves the ship to the waypoint 7 times (a total of 70 units east and 28 units north), leaving the ship at east 170, north 38. The waypoint stays 10 units east and 4 units north of the ship.
    R90 rotates the waypoint around the ship clockwise 90 degrees, moving it to 4 units east and 10 units south of the ship. The ship remains at east 170, north 38.
    F11 moves the ship to the waypoint 11 times (a total of 44 units east and 110 units south), leaving the ship at east 214, south 72. The waypoint stays 4 units east and 10 units south of the ship.

After these operations, the ship's Manhattan distance from its starting position is 214 + 72 = 286.

Figure out where the navigation instructions actually lead. What is the Manhattan distance between that location and the ship's starting position?
"""
def main(text):
    x_coord = 10
    y_coord = 1
    ship = [0, 0]
    for line in text.split('\n'):
        action = line[0]
        magnitude = int(line[1:])

        if action == 'N':
            y_coord += magnitude
        elif action == 'S':
            y_coord -= magnitude
        elif action == 'E':
            x_coord += magnitude
        elif action == 'W':
            x_coord -= magnitude
        elif action == 'L' or action == 'R':
            angle = (magnitude * (-1 if action == 'R' else 1)) % 360
            if angle == 90:
                x_coord, y_coord = -y_coord, x_coord
            elif angle == 180:
                x_coord, y_coord = -x_coord, -y_coord
            elif angle == 270:
                x_coord, y_coord = y_coord, -x_coord
        elif action == 'F':
            ship[0] += magnitude * x_coord
            ship[1] += magnitude * y_coord
    return abs(ship[0]) + abs(ship[1])


if __name__ == '__main__':
    with open('day12input') as f:
        print(main(f.read()[:-1]))
