#!/usr/bin/env python3
"""
--- Part Two ---

The Elves in accounting are thankful for your help; one of them even offers you a starfish coin they had left over from a past vacation. They offer you a second one if you can find three numbers in your expense report that meet the same criteria.

Using the above example again, the three entries that sum to 2020 are 979, 366, and 675. Multiplying them together produces the answer, 241861950.

In your expense report, what is the product of the three entries that sum to 2020?
"""
def main(text):
    expenses = sorted(map(int, text.split('\n')))
    
    for idx, expense in enumerate(expenses):
        total = 2020 - expense

        front = 0
        back = len(expenses) - 1
        while front != back:
            if front == idx:
                front += 1
            elif back == idx:
                back -= 1

            subtotal = expenses[front] + expenses[back]
            if subtotal > total:
                back -= 1
            elif subtotal < total:
                front += 1
            else:
                return expenses[front] * expenses[back] * expense

if __name__ == '__main__':
    with open('day1input') as f:
        print(main(f.read()[:-1]))
