#!/usr/bin/env python3
"""
--- Part Two ---

Time to check the rest of the slopes - you need to minimize the probability of a sudden arboreal stop, after all.

Determine the number of trees you would encounter if, for each of the following slopes, you start at the top-left corner and traverse the map all the way to the bottom:

    Right 1, down 1.
    Right 3, down 1. (This is the slope you already checked.)
    Right 5, down 1.
    Right 7, down 1.
    Right 1, down 2.

In the above example, these slopes would find 2, 7, 3, 4, and 2 tree(s) respectively; multiplied together, these produce the answer 336.

What do you get if you multiply together the number of trees encountered on each of the listed slopes?
"""
def main(text):
    grid = text.split('\n')
    slopes = (
        (1, 1),
        (3, 1),
        (5, 1),
        (7, 1),
        (1, 2)
    )
    result = 1
    for right, down in slopes:
        result *= check_slope(grid, right, down)
    return result


def check_slope(grid, right, down):
    width = len(grid[0])
    try:
        trees = 0
        row = down
        column = right
        while True:
            if grid[row][column] == '#':
                trees += 1
            row += down
            column = (column + right) % width
    except IndexError:
        return trees


if __name__ == '__main__':
    with open('day3input') as f:
        print(main(f.read()[:-1]))
