#!/usr/bin/env python3
"""
--- Part Two ---

Ding! The "fasten seat belt" signs have turned on. Time to find your seat.

It's a completely full flight, so your seat should be the only missing boarding pass in your list. However, there's a catch: some of the seats at the very front and back of the plane don't exist on this aircraft, so they'll be missing from your list as well.

Your seat wasn't at the very front or back, though; the seats with IDs +1 and -1 from yours will be in your list.

What is the ID of your seat?
"""
def main(text):
    seats = sorted(map(seat_to_id, text.split('\n')))
    for idx, seat in enumerate(seats):
        if seat + 1 != seats[idx+1]:
            return seat + 1


def seat_to_id(seat):
    row = int(seat[:7].replace('F', '0').replace('B', '1'), 2)
    column = int(seat[7:].replace('L', '0').replace('R', '1'), 2)
    return 8*row + column


if __name__ == '__main__':
    with open('day5input') as f:
        print(main(f.read()[:-1]))
