#!/usr/bin/env python3
"""
--- Part Two ---

After some careful analysis, you believe that exactly one instruction is corrupted.

Somewhere in the program, either a jmp is supposed to be a nop, or a nop is supposed to be a jmp. (No acc instructions were harmed in the corruption of this boot code.)

The program is supposed to terminate by attempting to execute an instruction immediately after the last instruction in the file. By changing exactly one jmp or nop, you can repair the boot code and make it terminate correctly.

For example, consider the same program from above:

nop +0
acc +1
jmp +4
acc +3
jmp -3
acc -99
acc +1
jmp -4
acc +6

If you change the first instruction from nop +0 to jmp +0, it would create a single-instruction infinite loop, never leaving that instruction. If you change almost any of the jmp instructions, the program will still eventually find another jmp instruction and loop forever.

However, if you change the second-to-last instruction (from jmp -4 to nop -4), the program terminates! The instructions are visited in this order:

nop +0  | 1
acc +1  | 2
jmp +4  | 3
acc +3  |
jmp -3  |
acc -99 |
acc +1  | 4
nop -4  | 5
acc +6  | 6

After the last instruction (acc +6), the program terminates by attempting to run the instruction below the last instruction in the file. With this change, after the program terminates, the accumulator contains the value 8 (acc +1, acc +1, acc +6).

Fix the program so that it terminates normally by changing exactly one jmp (to nop) or nop (to jmp). What is the value of the accumulator after the program terminates?
"""
def main(text):
    commands = text.split('\n')
    index = 0
    visited = {index}
    to_change = set()
    while True:
        next_command = commands[index]
        if next_command.startswith('nop'):
            to_change.add(index)
            index += 1
        elif next_command.startswith('acc'):
            index += 1
        elif next_command.startswith('jmp'):
            to_change.add(index)
            index += int(next_command[4:])
        
        if index in visited:
            break
        else:
            visited.add(index)

    total = len(commands)
    for index in to_change:
        old_command = commands[index][0:]
        if commands[index].startswith('nop'):
            commands[index] = commands[index].replace('nop', 'jmp')
        elif commands[index].startswith('jmp'):
            commands[index] = commands[index].replace('jmp', 'nop')
        
        idx = 0
        accumulator = 0
        visited = set()
        while True:
            if idx == total:
                return accumulator
            elif idx in visited:
                break
            else:
                visited.add(idx)
    
            next_command = commands[idx]
            if next_command.startswith('nop'):
                idx += 1
            elif next_command.startswith('acc'):
                idx += 1
                accumulator += int(next_command[4:])
            elif next_command.startswith('jmp'):
                idx += int(next_command[4:])

        commands[index] = old_command


if __name__ == '__main__':
    with open('day8input') as f:
        print(main(f.read()[:-1]))
