#!/usr/bin/env python3

import importlib
import sys

day = sys.argv[1]
part = sys.argv[2]

with open(f'day{day}input.txt') as f:
    module = importlib.import_module(f'day{day}')
    inp = f.read()[:-1]
    read_input = getattr(module, 'read_input')
    inp = read_input(inp)
    print(getattr(module, f'part{part}')(inp))
